# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b35e5b03ab26ab59b8e334fb27729911a2524620443abc3d69b26b6452c06781f370ad838b0f6ee80d3e4a3540518521ff91ebd97841b197e60241aac163847

test:
  secret_key_base: af04effe8b499b29193c80f6c0a2e4095152c0c3ea697f51914136a9189141cab495eadf0deef48859bf24f4f3693b2a38f588a3aa2198f962df6a14a2fa9252

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
